### ISSUE TITLE
Include main content section on home page

### ISSUE THREAD

**Issue by saracope** [saracope/open-gsa#12]
Include data, api, and code section under personas - pics, text

**Comment by saracope** [comment]
@jcastle: Did a first pass at this section if you want to take a look. The role-based section will still go above it when we add that in.

**Comment by jcastle-zz** [comment]
@saracope like the first pass.  Images for code, apis, and data are cool.  They look off center though.  Footer looks legit.  Awesome!  Keep on moving forward, this makes me very excited.

**Comment by jcastle-zz** [comment]
Think the upper left should include the GSA logo (it already does) and should have the title of:

GSA Open Technology or GSA Open (since the site is open.gsa.gov).  Thoughts?

**Comment by saracope** [comment]
Yeah, we have issue #9 open for the title.
